### PR TITLE
step 4 of instruction

### PR DESCRIPTION
**Pull request by smoussadeq**

### CODE REVIEW

**Comment by halfaro1** [comment]
@smoussadeq let me know if you need help, it looks like you still haven't had a chance to submit a passing automated test

**Comment by smoussadeq** [comment]
I don't know sir! I tried so may times. Can you please what the problem is ? or can you give me a chance to start all over again ?


________________________________

**Comment by halfaro1** [comment]
@smoussadeq I think I answered your question in an email. Let me know if it still doesn't make sense.

**Comment by smoussadeq** [comment]
I am trying to submit my homework again. I did everything is says but still it fails. I really don't understand. your help will be greatly appreciated!

**Comment by smoussadeq** [comment]
it keeps failing for step 10 and 11

**Comment by halfaro1** [comment]
@smoussadeq did you read my email? I'm trying to point out what's going on in there.

**Comment by smoussadeq** [comment]
Hello Professor! Will you please update my grade for tutorial1 ?
I just happen to find out to pass it
Thank you so much

**Comment by halfaro1** [comment]
@smoussadeq I'll update the grade soon. Good work on getting this taken care of.

**Pull request closed without merging**
